### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by clairekrogers** [DaC00P/tablegetter#1]
* Don't work from back-end to front-end, bring one feature at a time all the way through the process.  Start with reservations, get the back-end set up, then the flux architecture on the front-end.  After that, go through the same process with reviews, etc.  Restructure the timeline to match this process.
* Don't leave styling to the end - do it in parallel with the above process.  A feature should not be checked off the list until it is sufficiently styled.
* Overall, looks good!

**Comment by DaC00P** [comment]
Thank you for quick feedback! Will change the order around tonight & insert 0.5-1 days in between each feature for styling

**Comment by DaC00P** [comment]
Changed timeline to reflect feature by feature code progress
