### ISSUE TITLE
Wireframes missing

### ISSUE THREAD

**Issue by clairekrogers** [DaC00P/tablegetter#2]

**Comment by DaC00P** [comment]
Wireframes are present in Wireframes folder but not properly linked yet, will update.

**Comment by DaC00P** [comment]
Wireframes linked into .md, however, they are showing up sideways but the raw isn't oriented sideways. I think this is due to EXIF data, unsure how to fix without re-uploading with fixed orientation.

**Comment by DaC00P** [comment]
wireframes present, please view in raw for a rotated view
