### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by clairekrogers** [DaC00P/tablegetter#4]
* User and session routes should be namespaced under API.  We require front-end auth and single-page apps. 
* Reservations and Reviews: avoid deeply nested routes.  For example, just make a GET request to `/api/reviews` and pass in params to indicate which restaurant you wish to query

**Comment by DaC00P** [comment]
Question: Why should I avoid nesting everything under Restaurants? It seems like a cleaner way of approaching it in my limited experience.

**Comment by DaC00P** [comment]
fixed
