### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by clairekrogers** [DaC00P/tablegetter#5]
* Should datetime column be a string?  Not sure, but datetime might be a reserved word in postgres.  
* Reservations and Reviews: `description` column type should be `text` not `string`
* Join tables: naming convention is snake_case

**Comment by DaC00P** [comment]
Good points - I will look into postgres reserved keywords and change the data types. Will correct join tables as well.

**Comment by DaC00P** [comment]
datetime is  not reserved, made the other changes.
